# default: &default
#   adapter: postgresql
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: sathwik
#   password: sath139
#   host: postgres
#   database: casanova_prod

# development:
#   <<: *default
#   database: casanova_dev

# test:
#   <<: *default
#   database: casanova_test

# production:
#   <<: *default
#   database: casanova_prod

default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgresql://sathwik:sath139@localhost:5432/casanova_dev' %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgresql://sathwik:sath139@localhost:5432/casanova_test' %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'postgresql://sathwik:sath139@localhost:5432/casanova_prod' %>

