version: '3.9'
services:
  backend:
    image: casanova:rails-v1
    environment:
      RAILS_ENV: production
    ports:
      - 3001:3001

  frontend:
    image: casanova:react-v1
    environment:
      REACT_APP_HOST: localhost
    ports:
      - 3000:3000

